### ISSUE TITLE
Make the Project problem

### ISSUE THREAD

**Issue by ArionTT** [natelong/bgfx-js#1]
Hi, this project is great.
But when I try to compile the latest version of bgfx by emcc, I have meet some mistakes.
What the version was it supported?

**Comment by natelong** [comment]
Hi there!

I'm glad you're interested, but this is only still around as an archive for me. It was a proof of concept I did once, but only got to the point where a single cube would render. So much has changed since then that your best bet is probably to start a new set of JS bindings for bgfx. This project was probably built with a version of bgfx somewhere around https://github.com/bkaradzic/bgfx/commit/801207ffa755e3008c4fa1a18a2052ff630c0de2, which is about 3,500 commits ago. I bet bkaradzic has added a whole lot of great changes since then that are worth using.

Sorry I can't help more!
